encryptionsalt: v1:rV0zTuyhL1I=:v1:rVs6gsHf68kBZE00:oRRtqKTQV/ney9OxN8oe7BQjL63wKw==
config:
  demo:adminPassword:
    secure: v1:OHzvVrY+1TPt9r6n:wZiefUkhQVZ+jYnFTA0Xxv9DxD38xSSr
  demo:client_secret:
    secure: v1:b3h2I9JITs54wYaO:gJlKMo198vOUVjDfWRDiAqXPhP4g9zIPD8+cUhDh1nVG3V6l3j/48nubF5DjRUKAhMCGLpFbPfQ=
  kubernetes:context: kubernetes-admin@norther
