{
 "title": "VMware vSphere Overview",
 "tags": [ "Platform" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds, customer)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds{customer=\"$customer\"}, dc_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds{customer=\"$customer\",dc_name=\"$datacenter\"}, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumed CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usage{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}) / sum(vmware_host_cpu_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Consumed Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}) / sum(vmware_host_memory_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Hypervisor Scaler",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(vmware_host_power_state{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"})",
     "legendFormat": "hypervisor"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_datastore_capacity_size{customer=\"$customer\",dc_name=\"$datacenter\",ds_name!~\"local-.*\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"} * 1000000"
    },
    {
     "expr": "vmware_vm_mem_consumed_average{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_datastore_capacity_size{customer=\"$customer\",dc_name=\"$datacenter\",ds_name!~\"local-.*\"}) - sum(vmware_datastore_freespace_size{customer=\"$customer\",dc_name=\"$datacenter\",ds_name!~\"local-.*\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vmware_datastore_freespace_size{customer=\"$customer\",dc_name=\"$datacenter\",ds_name!~\"local-.*\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(vmware_datastore_provisoned_size{customer=\"$customer\",dc_name=\"$datacenter\",ds_name!~\"local-.*\"})",
     "legendFormat": "Provisoned"
    }
   ]
  },
  {
   "title": "Max Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"})"
    }
   ]
  },
  { "title": "Hypervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "vmware_host_memory_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "vmware_host_cpu_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "time() - vmware_host_boot_timestamp_seconds{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "vmware_host_product_info{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "vmware_host_hardware_info{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "vmware_host_num_cpu{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "vmware_host_cpu_usage{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"} / vmware_host_cpu_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "vmware_host_memory_usage{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"} / vmware_host_memory_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "vmware_host_red_alarms{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}"
    },
    {
     "expr": "sum (vmware_vm_power_state{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"} == 1) by (host_name)"
    },
    {
     "expr": "sum(vmware_vm_max_cpu_usage{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}) by (host_name) / sum (vmware_host_cpu_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}) by (host_name)"
    },
    {
     "expr": "sum(vmware_vm_memory_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}) by (host_name) / sum (vmware_host_memory_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}) by (host_name)"
    }
   ]
  },
  {
   "title": "Consumed CPU %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"} / vmware_host_cpu_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  {
   "title": "Consumed Memory %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vmware_host_memory_usage{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"} / vmware_host_memory_max{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  {
   "title": "Disk Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Kibits" } },
   "targets": [
    {
     "expr": "vmware_host_disk_read_average{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}",
     "legendFormat": "Read: {{ host_name }}"
    },
    {
     "expr": "vmware_host_disk_write_average{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}",
     "legendFormat": "Write: {{ host_name }}"
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "vmware_host_net_bytesRx_average{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}",
     "legendFormat": "Received: {{ host_name }}"
    },
    {
     "expr": "- vmware_host_net_bytesTx_average{customer=\"$customer\",dc_name=\"$datacenter\",cluster_name=\"$cluster\"}",
     "legendFormat": "Transmitted:  {{ host_name }}"
    }
   ]
  }
 ]
}