{
 "title": "Cross Server Graphs",
 "tags": [ "OS" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(node_time_seconds, customer)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_time_seconds{customer=\"$customer\"}, environment)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(node_time_seconds{customer=\"$customer\",environment=~\"$environment\"}, project)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_time_seconds{customer=\"$customer\",environment=~\"$environment\",project=~\"$project\"},group)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_time_seconds{customer=\"$customer\",environment=~\"$environment\",project=~\"$project\",group=~\"$group\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Specifications",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(node_os_info{instance=~\"$host\"}) by (instance,pretty_name)"
    },
    {
     "expr": "count(node_cpu_info{cpu=\"0\",instance=~\"$host\"}) by (datacenter,customer,environment,project,group,instance,model_name)"
    },
    {
     "expr": "sum by(instance)(windows_cs_logical_processors{instance=~\"$host\"}) or count by(instance)(node_cpu_seconds_total{instance=~\"$host\",mode=\"user\"})"
    },
    {
     "expr": "(sum by(instance)(node_memory_MemTotal_bytes{instance=~\"$host\"}) or sum by(instance)(windows_os_visible_memory_bytes{instance=~\"$host\"}))"
    },
    {
     "expr": "sum by(instance)(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) + sum by(instance)(node_memory_SwapTotal_bytes{instance=~\"$host\"}) or sum by(instance)(windows_logical_disk_size_bytes{instance=~\"$host\"})"
    },
    {
     "expr": "(time() - sum by (instance)(node_boot_time_seconds{instance=~\"$host\"})) or (time() - sum by (instance)(windows_system_system_up_time{instance=~\"$host\"}))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(node_memory_MemTotal_bytes{instance=~\"$host\"}) or vector(0)) + (count(windows_os_visible_memory_bytes{instance=~\"$host\"}) or vector(0))",
     "legendFormat": "Instance"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(windows_cs_logical_processors{instance=~\"$host\"}) or vector(0)) + (count(node_cpu_seconds_total{instance=~\"$host\",mode=\"user\"}) or vector(0))",
     "legendFormat": "VCore"
    },
    {
     "expr": "((sum(node_memory_MemTotal_bytes{instance=~\"$host\"}) or vector(0)) + (sum(windows_os_visible_memory_bytes{instance=~\"$host\"}) or vector(0)))",
     "legendFormat": "Memory"
    },
    {
     "expr": "((sum(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) or vector(0)) + (sum(node_memory_SwapTotal_bytes{instance=~\"$host\"}) or vector(0)) + (sum(windows_logical_disk_size_bytes{instance=~\"$host\"}) or vector(0)))",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Combine CPU Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$host\",mode='idle'}[5m]))) or (1 - avg(irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$host\"}[5m])))",
     "legendFormat": "Usage"
    },
    {
     "expr": "(1 - (1 - avg(irate(node_cpu_seconds_total{instance=~\"$host\",mode='idle'}[5m])))) or (1 - (1 - avg(irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$host\"}[5m]))))",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes{instance=~\"$host\"} - (node_memory_MemFree_bytes{instance=~\"$host\"} + node_memory_Buffers_bytes{instance=~\"$host\"} + node_memory_Cached_bytes{instance=~\"$host\"})) / node_memory_MemTotal_bytes{instance=~\"$host\"}) or avg((windows_cs_physical_memory_bytes{instance=~\"$host\"} - windows_os_physical_memory_free_bytes{instance=~\"$host\"}) / windows_cs_physical_memory_bytes{instance=~\"$host\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "(1 - avg((node_memory_MemTotal_bytes{instance=~\"$host\"} - (node_memory_MemFree_bytes{instance=~\"$host\"} + node_memory_Buffers_bytes{instance=~\"$host\"} + node_memory_Cached_bytes{instance=~\"$host\"})) / node_memory_MemTotal_bytes{instance=~\"$host\"})) or (1 - avg((windows_cs_physical_memory_bytes{instance=~\"$host\"} - windows_os_physical_memory_free_bytes{instance=~\"$host\"}) / windows_cs_physical_memory_bytes{instance=~\"$host\"}))",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disc Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1- sum(node_filesystem_free_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) / sum (node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})) or (1- sum(windows_logical_disk_free_bytes{instance=~\"$host\"}) / sum(windows_logical_disk_size_bytes{instance=~\"$host\"}))",
     "legendFormat": "Usage"
    },
    {
     "expr": "(sum(node_filesystem_free_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) / sum (node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})) or (sum(windows_logical_disk_free_bytes{instance=~\"$host\"}) / sum(windows_logical_disk_size_bytes{instance=~\"$host\"}))",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Combine CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(100 - avg by(instance)(irate(node_cpu_seconds_total{instance=~\"$host\",mode='idle'}[5m])) * 100) or (100 - avg by(instance)(irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$host\"}[5m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$host\"} - (node_memory_MemFree_bytes{instance=~\"$host\"} + node_memory_Buffers_bytes{instance=~\"$host\"} + node_memory_Cached_bytes{instance=~\"$host\"})) / node_memory_MemTotal_bytes{instance=~\"$host\"}) * 100 or ((windows_cs_physical_memory_bytes{instance=~\"$host\"} - windows_os_physical_memory_free_bytes{instance=~\"$host\"}) / windows_cs_physical_memory_bytes{instance=~\"$host\"}) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disc Usage",
   "type": "graph",
   "description": "Percentage of usage disk space on mount for Linux.\nPercentage of usage disk space exclude reserve partition for Windows.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(1- sum by(instance)(node_filesystem_free_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) / sum by(instance)(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})) * 100 or (1- sum by(instance)(windows_logical_disk_free_bytes{instance=~\"$host\"}) / sum by(instance)(windows_logical_disk_size_bytes{instance=~\"$host\"})) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}