{
 "title": "Kubernetes Cluster",
 "tags": [
  "Platform",
  "Kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(machine_cpu_cores, customer)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(machine_cpu_cores{customer=\"$customer\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(machine_cpu_cores{customer=\"$customer\",environment=\"$environment\"}, group)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_status_phase{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU Usage",
   "type": "gauge",
   "description": "Container CPU usage may be completely different from IaaS or Hypervisor.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\",group=\"$cluster\",customer=\"$customer\",environment=\"$environment\"}[5m])) / sum (machine_cpu_cores{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}) / sum(machine_memory_bytes{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"})"
    }
   ]
  },
  {
   "title": "Container Network Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}[5m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Cluster Node Scaler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_node_labels{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"})",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\",group=\"$cluster\",customer=\"$customer\",environment=\"$environment\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"})"
    }
   ]
  },
  { "title": "Hypervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Resource",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(node)(kube_node_labels{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"})"
    },
    {
     "expr": "count by(node)(label_replace(node_cpu_seconds_total{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\",mode=\"idle\"}, \"node\", \"$1\", \"instance\", \"(.*)\"))"
    },
    {
     "expr": "sum by (node)(label_replace(node_memory_MemTotal_bytes{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\"))"
    },
    {
     "expr": "(1- avg by(node)(label_replace(irate(node_cpu_seconds_total{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\",mode='idle'}[5m]),\"node\", \"$1\", \"instance\", \"(.*)\"))) * 100"
    },
    {
     "expr": "((label_replace(node_memory_MemTotal_bytes{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\") - (label_replace(node_memory_MemFree_bytes{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\") + label_replace(node_memory_Buffers_bytes{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\") + label_replace(node_memory_Cached_bytes{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\"))) / label_replace(node_memory_MemTotal_bytes{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) * 100"
    },
    {
     "expr": "time() - label_replace(node_boot_time_seconds{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"},\"node\", \"$1\", \"instance\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(node_filesystem_size_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}) by (instance),\"node\", \"$1\", \"instance\", \"(.*)\")"
    },
    {
     "expr": "(1- sum by(node)(label_replace(node_filesystem_free_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"},\"node\", \"$1\", \"instance\", \"(.*)\")) / sum by(node)(label_replace(node_filesystem_size_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\",customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"},\"node\", \"$1\", \"instance\", \"(.*)\"))) * 100"
    },
    {
     "expr": "kube_node_spec_unschedulable{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}"
    },
    {
     "expr": "label_replace(count(node_cpu_info{cpu=\"0\",customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}) by (instance,model_name),\"node\", \"$1\", \"instance\", \"(.*)\")"
    },
    {
     "expr": "kube_node_info{customer=\"$customer\",environment=\"$environment\",group=\"$cluster\"}"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Unsuccessful Pods",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (namespace,phase,pod)(kube_pod_status_phase{namespace=~\"$namespace\",group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",phase=~\"Failed|Pending|Unknown\"}==1)"
    }
   ]
  },
  {
   "title": "PVs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_resource_requests_storage_bytes{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",group=\"$cluster\",environment=\"$environment\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Statefulsets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_created{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod!=\"\",group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",image!=\"\",container!=\"\"})"
    }
   ]
  },
  {
   "title": "PV Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Limits Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",group=\"$cluster\",environment=\"$environment\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Limits Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Daemonsets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_daemonset_created{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Configmap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_configmap_created{group=\"$cluster\",environment=\"$environment\",customer=\"$customer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace=~\"$namespace\",group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\",unit=\"core\"}) by (namespace,pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\",unit=\"core\"}) by (namespace,pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\",unit=\"byte\"}) by (namespace,pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\",unit=\"byte\"}) by (namespace,pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\",namespace=~\"$namespace\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}[5m])) by (namespace,pod) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\",unit=\"core\"}) by (namespace,pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",pod!=\"\",namespace=~\"$namespace\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}) by (namespace,pod) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\",unit=\"byte\"}) by (namespace,pod)"
    }
   ]
  },
  { "title": "Pods Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\",container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod!=\"\",cluster=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "System Services CPU and Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "System services CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"kube-.*\",pod!=\"\",group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container!=\"\",namespace=~\"kube-.*\",pod!=\"\",group=\"$cluster\",environment=\"$environment\",customer=\"$customer\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}