{
 "title": "Linux Network Overview",
 "description": "Linux Network Overview",
 "tags": [
  "OS",
  "Linux"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(node_network_receive_packets_total, customer)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_network_receive_packets_total{customer=\"$customer\"}, environment)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(node_network_receive_packets_total{customer=\"$customer\",environment=\"$environment\"}, project)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_network_receive_packets_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, group)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_network_receive_packets_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "Interface",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",instance=\"$host\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Last Hour statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inbound Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"$device\",instance=\"$host\"}[1h]))"
    }
   ]
  },
  {
   "title": "Outbound Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=\"$device\",instance=\"$host\"}[1h]))"
    }
   ]
  },
  {
   "title": "Traffic Errors and Drops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_errs_total{instance=\"$host\", device=\"$device\"}[1h])) +\nsum(increase(node_network_transmit_errs_total{instance=\"$host\", device=\"$device\"}[1h])) +\nsum(increase(node_network_receive_drop_total{instance=\"$host\", device=\"$device\"}[1h])) +\nsum(increase(node_network_transmit_drop_total{instance=\"$host\", device=\"$device\"}[1h]))"
    }
   ]
  },
  {
   "title": "Retransmit rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[1h]) * 100 / (rate(node_netstat_Tcp_OutSegs{instance=\"$host\"}[1h]) + rate(node_netstat_Tcp_InSegs{instance=\"$host\"}[1h]))"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$host\", device=\"$device\"}[$interval])) or \nsum(irate(node_network_receive_bytes_total{instance=\"$host\", device=\"$device\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[5m])) ",
     "legendFormat": "{{ $device }}: Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$host\", device=\"$device\"}[$interval])) or \nsum(irate(node_network_transmit_bytes_total{instance=\"$host\", device=\"$device\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[5m]))",
     "legendFormat": "{{ $device }}: Outbound"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$host\", device=\"$device\"}[1h]))",
     "legendFormat": "{{ $device }}: Inbound"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$host\", device=\"$device\"}[1h]))",
     "legendFormat": "{{ $device }}: Outbound"
    }
   ]
  },
  { "title": "Network traffic details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_receive_packets_total{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_packets_total{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{instance=\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_receive_errs_total{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{instance=\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_transmit_errs_total{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{instance=\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_drop_total{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{instance=\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_drop_total{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_multicast_total{instance=\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_multicast_total{instance=\"$host\", device!=\"lo\"}[5m])",
     "legendFormat": "{{device}} - Receive multicast"
    }
   ]
  },
  { "title": "Network Netstat TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Netstat: TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(node_netstat_Tcp_CurrEstab{instance=\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_CurrEstab{instance=\"$host\"}[5m])",
     "legendFormat": "established"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_ActiveOpens{instance=\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_ActiveOpens{instance=\"$host\"}[5m])",
     "legendFormat": "activeOpens"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_PassiveOpens{instance=\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_PassiveOpens{instance=\"$host\"}[5m])",
     "legendFormat": "passiveOpens"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_EstabResets{instance=\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_EstabResets{instance=\"$host\"}[5m])",
     "legendFormat": "estabResets"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_AttemptFails{instance=\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_AttemptFails{instance=\"$host\"}[5m])",
     "legendFormat": "attemptfails"
    },
    {
     "expr": "max_over_time(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[$interval]) or\nmax_over_time(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[5m])",
     "legendFormat": "retransSegs"
    }
   ]
  },
  {
   "title": "TCP Segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InCsumErrors{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_InCsumErrors{instance=\"$host\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_InErrs{instance=\"$host\"}[5m])",
     "legendFormat": "InErrs "
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_InSegs{instance=\"$host\"}[5m])",
     "legendFormat": "InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutRsts{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_OutRsts{instance=\"$host\"}[5m])",
     "legendFormat": "OutRsts"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_OutSegs{instance=\"$host\"}[5m])",
     "legendFormat": "OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[5m])",
     "legendFormat": "RetransSegs"
    }
   ]
  },
  { "title": "Network Netstat UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Netstat: UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Udp_InDatagrams{instance=\"$host\"}[$interval]) or irate(node_netstat_Udp_InDatagrams{instance=\"$host\"}[5m]))",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InErrors{instance=\"$host\"}[$interval]) or irate(node_netstat_Udp_InErrors{instance=\"$host\"}[5m]))",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_OutDatagrams{instance=\"$host\"}[$interval]) or irate(node_netstat_Udp_OutDatagrams{instance=\"$host\"}[5m]))",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_NoPorts{instance=\"$host\"}[$interval]) or irate(node_netstat_Udp_NoPorts{instance=\"$host\"}[5m]))",
     "legendFormat": "Udp_NoPorts"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_InCsumErrors{instance=\"$host\"}[$interval]) or irate(node_netstat_Udp_InCsumErrors{instance=\"$host\"}[5m]))",
     "legendFormat": "Udp_InCsumErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_RcvbufErrors{instance=\"$host\"}[$interval]) or irate(node_netstat_Udp_RcvbufErrors{instance=\"$host\"}[5m]))",
     "legendFormat": "Udp_RcvbufErrors"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_SndbufErrors{instance=\"$node\"}[$interval]) or irate(node_netstat_Udp_SndbufErrors{instance=\"$host\"}[5m]))",
     "legendFormat": "Udp_SndbufErrors"
    }
   ]
  },
  { "title": "ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Messages / Redirects",
   "type": "graph",
   "description": "**InMsgs**  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors\t\n\n**InRedirects**  Redirect messages received\t\n\n**OutMsgs**  Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors\t\n\n**OutRedirects** Redirect messages sent. For a host, this object will always be zero, since hosts do not send redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ops", "label": "Out (-) / In (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InMsgs{instance=\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_InMsgs{instance=\"$host\"}[5m])",
     "legendFormat": "InMsgs "
    },
    {
     "expr": "rate(node_netstat_Icmp_OutMsgs{instance=\"$host\"}[$interval]) or\nirate(node_netstat_Icmp_OutMsgs{instance=\"$host\"}[5m])",
     "legendFormat": "OutMsgs"
    }
   ]
  }
 ]
}