{
 "title": "Linux System Overview",
 "description": "Linux System Overview",
 "tags": [
  "OS",
  "Linux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(node_load1, customer)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_load1{customer=\"$customer\"}, environment)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(node_load1{customer=\"$customer\",environment=\"$environment\"}, project)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_load1{customer=\"$customer\",environment=\"$environment\",project=\"$project\"}, group)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_load1{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"},instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(os_info{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\",instance=\"$host\"},interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_time_seconds{instance=\"$host\"} - node_boot_time_seconds{instance=\"$host\"}) or (time() - node_boot_time_seconds{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_os_info{instance=\"$host\"}",
     "legendFormat": "{{ pretty_name }}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_cpu_info{cpu=\"0\",instance=\"$host\"}",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "VCores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{instance=\"$host\",mode=\"user\"}) or (1-absent(node_cpu_seconds_total{instance=\"$host\",mode=\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{instance=\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "stat",
   "description": "Memory + SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}+node_memory_SwapTotal_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) + sum(node_memory_SwapTotal_bytes{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU Saturation and Max Core Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(avg_over_time(node_procs_running{instance=\"$host\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=\"$host\"})) or (avg_over_time(node_procs_running{instance=\"$host\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=\"$host\"}))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max CPU Core Utilization"
    }
   ]
  },
  {
   "title": "Interrupts and Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_context_switches_total{instance=\"$host\"}[$interval]) or irate(node_context_switches_total{instance=\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "(rate(node_context_switches_total{instance=\"$host\"}[$interval]) or irate(node_context_switches_total{instance=\"$host\"}[5m])) / scalar(count(node_cpu_guest_seconds_total{mode=\"user\", instance=\"$host\"}))",
     "legendFormat": "Context Switches per Virtual CPU"
    },
    {
     "expr": "rate(node_intr_total{instance=\"$host\"}[$interval]) or irate(node_intr_total{instance=\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(avg_over_time(node_procs_running{instance=\"$host\"}[$interval]) - 1) or (avg_over_time(node_procs_running{instance=\"$host\"}[5m]) -1)",
     "legendFormat": "Runnable Processes"
    },
    {
     "expr": "avg_over_time(node_procs_blocked{instance=\"$host\"}[$interval]) or avg_over_time(node_procs_blocked{instance=\"$host\"}[5m])",
     "legendFormat": "Blocked Processes"
    },
    {
     "expr": "rate(node_forks_total{instance=\"$host\"}[$interval]) or irate(node_forks_total{instance=\"$host\"}[5m])",
     "legendFormat": "Created Processes (Forks)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree_bytes{instance=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers_bytes{instance=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached_bytes{instance=\"$host\"}",
     "legendFormat": "Cached"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"} - (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Virtual Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}+node_memory_SwapTotal_bytes{instance=\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "(node_memory_MemAvailable_bytes{instance=\"$host\"} or (node_memory_MemFree_bytes{instance=\"$host\"}) + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"}) + node_memory_SwapFree_bytes{instance=\"$host\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}+node_memory_SwapTotal_bytes{instance=\"$host\"} - ((node_memory_MemAvailable_bytes{instance=\"$host\"} or (node_memory_MemFree_bytes{instance=\"$host\"}) + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"}) + node_memory_SwapFree_bytes{instance=\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal_bytes{instance=\"$host\"} - node_memory_SwapFree_bytes{instance=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree_bytes{instance=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps", "label": "Swap out (-) / Swap in (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    },
    {
     "expr": "(rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096) + (rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "I/O Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "(rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024)",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "(rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Global File Descriptors Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_filefd_maximum{instance=\"$host\"}",
       "legendFormat": "Limit"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_filefd_allocated{instance=\"$host\"}",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "Disk IO Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(node_disk_read_time_ms{instance=\"$host\"}[$interval])) / sum(rate(node_disk_reads_completed{instance=\"$host\"}[$interval]))) or (sum(irate(node_disk_read_time_ms{instance=\"$host\"}[5m])) / sum(irate(node_disk_reads_completed{instance=\"$host\"}[5m])))\nor avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[$interval]) or avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[5m])",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "(sum(rate(node_disk_write_time_ms{instance=\"$host\"}[$interval])) / sum(rate(node_disk_writes_completed{instance=\"$host\"}[$interval]))) or (sum(irate(node_disk_write_time_ms{instance=\"$host\"}[5m])) / sum(irate(node_disk_writes_completed{instance=\"$host\"}[5m])))\nor (avg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[5m]))",
       "legendFormat": "Write Latency"
      },
      {
       "expr": "(sum(rate(node_disk_read_time_seconds_total{instance=\"$host\"}[1h])) / sum(rate(node_disk_reads_completed_total{instance=\"$host\"}[1h])))\nor avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[1h]) or avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[1h]) ",
       "legendFormat": "Avg Read Latency (1h)"
      },
      {
       "expr": "(sum(rate(node_disk_write_time_seconds_total{instance=\"$host\"}[1h])) / sum(rate(node_disk_writes_completed_total{instance=\"$host\"}[1h]))) \nor (avg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[1h]))",
       "legendFormat": "Avg Write Latency (1h)"
      }
     ]
    },
    {
     "title": "Disk IO Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Write Load (-) / Read Load (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(node_disk_read_time_seconds_total{instance=\"$host\"}[$interval]))/1000 or sum(irate(node_disk_read_time_seconds_total{instance=\"$host\"}[5m]))/1000",
       "legendFormat": "Read Load"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(node_disk_write_time_seconds_total{instance=\"$host\"}[$interval]))/1000 or sum(irate(node_disk_write_time_seconds_total{instance=\"$host\"}[5m]))/1000",
       "legendFormat": "Write Load"
      },
      {
       "expr": "(sum(rate(node_disk_read_time_seconds_total{instance=\"$host\"}[$interval]))/1000 or sum(irate(node_disk_read_time_seconds_total{instance=\"$host\"}[5m]))/1000) + (sum(rate(node_disk_write_time_seconds_total{instance=\"$host\"}[$interval]))/1000 or sum(irate(node_disk_write_time_seconds_total{instance=\"$host\"}[5m]))/1000)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$host\", device=\"$interface\"}[$interval])) or sum(irate(node_network_receive_bytes_total{instance=\"$host\", device=\"$interface\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[5m])) ",
       "legendFormat": "{{ $interface }}: Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[5m]))",
       "legendFormat": "{{ $interface }}: Outbound"
      }
     ]
    },
    {
     "title": "Network Utilization Hourly",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$host\", device=\"$interface\"}[1h])) or sum(increase(rdsosmetrics_network_rx{instance=\"$host\", device=\"$interface\"}[1h]))",
       "legendFormat": "{{ $interface}}: Received"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$host\", device=\"$interface\"}[1h])) or sum(increase(rdsosmetrics_network_tx{instance=\"$host\", device=\"$interface\"}[1h]))",
       "legendFormat": "{{ $interface }}: Sent"
      },
      {
       "expr": "(sum(increase(node_network_receive_bytes_total{instance=\"$host\", device=\"$interface\"}[1h]))+sum(increase(node_network_transmit_bytes_total{instance=\"$host\", device=\"$interface\"}[1h]))) or (sum(increase(rdsosmetrics_network_rx{instance=\"$host\", device=\"$interface\"}[1h]))+sum(increase(rdsosmetrics_network_tx{instance=\"$host\", device=\"$interface\"}[1h])))",
       "legendFormat": "{{ $interface }}:Total"
      }
     ]
    },
    {
     "title": "Local Network Errors",
     "type": "graph",
     "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_receive_errs_total{instance=\"$host\", device=\"$interface\"}[$interval])) or \nsum(irate(node_network_receive_errs_total{instance=\"$host\", device=\"$interface\"}[5m]))",
       "legendFormat": "{{ $interface}}: Receive Errors"
      },
      {
       "expr": "sum(rate(node_network_transmit_errs_total{instance=\"$host\", device=\"$interface\"}[$interval])) or\nsum(irate(node_network_transmit_errs_total{instance=\"$host\", device=\"$interface\"}[5m]))",
       "legendFormat": "{{ $interface }}: Transmit Errors"
      },
      {
       "expr": "sum(rate(node_network_receive_drop_total{instance=\"$host\", device=\"$interface\"}[$interval])) or\nsum(irate(node_network_receive_drop_total{instance=\"$host\", device=\"$interface\"}[5m]))",
       "legendFormat": "{{ $interface }}: Receive Drop"
      },
      {
       "expr": "sum(rate(node_network_transmit_drop_total{instance=\"$host\", device=\"$interface\"}[$interval])) or \nsum(irate(node_network_transmit_drop_total{instance=\"$host\", device=\"$interface\"}[5m]))",
       "legendFormat": "{{ $interface }}: Transmit Drop"
      }
     ]
    },
    {
     "title": "TCP Retransmission",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[5m])",
       "legendFormat": "Segments Retransmitted"
      },
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[$interval])/rate(node_netstat_Tcp_OutSegs{instance=\"$host\"}[$interval]) or irate(node_netstat_Tcp_RetransSegs{instance=\"$host\"}[5m])/irate(node_netstat_Tcp_OutSegs{instance=\"$host\"}[5m])",
       "legendFormat": "Retransmit Ratio"
      }
     ]
    }
   ]
  }
 ]
}