global:
  http_config:
    tls_config:
      insecure_skip_verify: true    
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 1m
  group_interval: 15s
  repeat_interval: 12h
  receiver: 'null'
  routes:
  - match:
      alertname: Watchdog
    receiver: 'null'
  - match:
    receiver: 'wechat'
    continue: true
  - match:
    receiver: 'alerta'
    continue: true
receivers:
- name: 'null'
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    to_party: '5'
    agent_id: '1000005'
    corp_id: 'wxe787605f1d1700da'
    api_secret: '0BfjWZhwqFi0IUHN8sMh0JEd89383iin1TTaJajJ_SI'
- name: 'alerta'
  webhook_configs:
  - send_resolved: true
    url: 'https://10.101.4.34:8443/api/webhooks/prometheus?api-key=jFiZhyFED477Ze4zfkNpP5-zBLXmqAhTSMATXeVm'
templates:
- '/etc/alertmanager/config/*.tmpl'