global:
  http_config:
    tls_config:
      insecure_skip_verify: true    
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 1m
  group_interval: 15s
  repeat_interval: 24h
  receiver: 'null'
  routes:
  - matchers:
    - severity=~"p1|p2"
    receiver: wechat
    continue: true
  - matchers:
    - alertname=Watchdog
    receiver: 'null'
inhibit_rules:
- source_match:
    severity: 'p1'
  target_match:
    severity: 'p2'
  equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'null'
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    to_party: '5'
    agent_id: '1000005'
    corp_id: 'wxe787605f1d1700da'
    api_secret: '0BfjWZhwqFi0IUHN8sMh0JEd89383iin1TTaJajJ_SI'
templates:
- '/etc/alertmanager/config/*.tmpl'