import * as k8s from "@pulumi/kubernetes";

const deploy_spec = [
    {
        namespace: {
            metadata: {
                name: "skywalking",
                annotations: {},
                labels: {}
            },
            spec: {}
        },
        helm: [
            {
                namespace: "skywalking",
                name: "elasticsearch",
                chart: "../../_chart/elasticsearch-19.3.0.tgz",
                repository: "",
                version: "19.3.0",
                values: {
                    image: { tag: "7.17.6-debian-11-r7" },
                    security: {
                        enabled: false,
                        elasticPassword: "password",
                        tls: {
                            autoGenerated: true,
                            verificationMode: "none"
                        }
                    },
                    name: "skywalking",
                    extraConfig: {
                        cluster: {
                            max_shards_per_node: 10000
                        }
                    },
                    master: {
                        replicaCount: 3,
                        heapSize: "128m",
                        podLabels: { customer: "demo", environment: "dev", project: "cluster", group: "norther", datacenter: "dc01", domain: "local" },
                        persistence: { storageClass: "longhorn", size: "8Gi" }
                    },

                    data: {
                        replicaCount: 1,
                        resources: {
                            limits: { cpu: "1000m", memory: "4096Mi" },
                            requests: { cpu: "1000m", memory: "4096Mi" }
                        },
                        heapSize: "3072m",
                        podLabels: { customer: "demo", environment: "dev", project: "cluster", group: "norther", datacenter: "dc01", domain: "local" },
                        persistence: { storageClass: "longhorn", size: "30Gi" }
                    },
                    coordinating: { replicaCount: 0 },
                    ingest: { enabled: false },
                    metrics: {
                        enabled: true,
                        resources: {
                            limits: { cpu: "100m", memory: "128Mi" },
                            requests: { cpu: "100m", memory: "128Mi" }
                        },
                        podLabels: { customer: "demo", environment: "dev", project: "cluster", group: "norther", datacenter: "dc01", domain: "local" },
                        serviceMonitor: {
                            enabled: true,
                            relabelings: [
                                { sourceLabels: ["__meta_kubernetes_pod_label_customer"], targetLabel: "customer" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_environment"], targetLabel: "environment" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_project"], targetLabel: "project" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_group"], targetLabel: "group" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_datacenter"], targetLabel: "datacenter" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_domain"], targetLabel: "domain" }
                            ],
                        },
                        prometheusRule: { enabled: true, rules: [] }
                    },
                    volumePermissions: {
                        enabled: true,
                        resources: {
                            limits: { cpu: "100m", memory: "128Mi" },
                            requests: { cpu: "100m", memory: "128Mi" }
                        }
                    },
                    sysctlImage: {
                        enabled: true,
                        resources: {
                            limits: { cpu: "100m", memory: "128Mi" },
                            requests: { cpu: "100m", memory: "128Mi" }
                        }
                    }
                }
            },
            {
                namespace: "skywalking",
                name: "kibana",
                chart: "../../_chart/kibana-10.2.2.tgz",
                repository: "",
                version: "10.2.2",
                values: {
                    image: { tag: "7.17.6-debian-11-r6" },
                    replicaCount: 1,
                    volumePermissions: {
                        enabled: true,
                        resources: {
                            limits: { cpu: "100m", memory: "128Mi" },
                            requests: { cpu: "100m", memory: "128Mi" }
                        }
                    },
                    persistence: { storageClass: "longhorn", size: "8Gi" },
                    ingress: {
                        enabled: true,
                        hostname: "kibana.example.com",
                        path: "/",
                        ingressClassName: "nginx",
                    },
                    resources: {
                        limits: { cpu: "100m", memory: "256Mi" },
                        requests: { cpu: "100m", memory: "256Mi" }
                    },
                    podLabels: { customer: "demo", environment: "dev", project: "cluster", group: "norther", datacenter: "dc01", domain: "local" },
                    metrics: {
                        enabled: true,
                        serviceMonitor: {
                            enabled: true,
                            relabelings: [
                                { sourceLabels: ["__meta_kubernetes_pod_label_customer"], targetLabel: "customer" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_environment"], targetLabel: "environment" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_project"], targetLabel: "project" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_group"], targetLabel: "group" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_datacenter"], targetLabel: "datacenter" },
                                { sourceLabels: ["__meta_kubernetes_pod_label_domain"], targetLabel: "domain" }
                            ],
                        }
                    },
                    elasticsearch: {
                        hosts: ["elasticsearch"],
                        port: "9200",
                        security: {
                            auth: {
                                enabled: false,
                                kibanaUsername: "elastic",
                                kibanaPassword: "password"
                            },
                            tls: {
                                enabled: true,
                                verificationMode: "none"
                            }
                        }
                    }
                }
            },
            {
                namespace: "skywalking",
                name: "skywalking",
                chart: "../../_chart/skywalking-4.2.0.tgz",
                repository: "",
                version: "4.2.0",
                values: {
                    oap: {
                        storageType: "elasticsearch",
                        replicas: 1,
                        image: { tag: "9.1.0" },
                        javaOpts: "-Xmx3g -Xms3g",
                        resources: {
                            limits: { cpu: "1000m", memory: "4096Mi" },
                            requests: { cpu: "1000m", memory: "4096Mi" }
                        }
                    },
                    ui: {
                        replicas: 1,
                        image: { tag: "9.1.0" },
                        ingress: {
                            enabled: true,
                            annotations: {
                                "kubernetes.io/ingress.class": "nginx"
                            },
                            hosts: ["skywalking.example.com"]
                        }
                    },
                    elasticsearch: { enabled: false }
                }
            }
        ]
    }
]

for (var i in deploy_spec) {
    // Create Kubernetes Namespace.
    const namespace = new k8s.core.v1.Namespace(deploy_spec[i].namespace.metadata.name, {
        metadata: deploy_spec[i].namespace.metadata,
        spec: deploy_spec[i].namespace.spec
    });
    // Create Release Resource.
    for (var helm_index in deploy_spec[i].helm) {
        const release = new k8s.helm.v3.Release(deploy_spec[i].helm[helm_index].name, {
            namespace: deploy_spec[i].helm[helm_index].namespace,
            name: deploy_spec[i].helm[helm_index].name,
            chart: deploy_spec[i].helm[helm_index].chart,
            version: deploy_spec[i].helm[helm_index].version,
            values: deploy_spec[i].helm[helm_index].values,
            skipAwait: true,
        }, { dependsOn: [namespace] });
    }
}