apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/instance: skywalking
    app.kubernetes.io/name: skywalking
  name: skywalking
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - skywalking
  podMetricsEndpoints:
  - interval: 60s
    path: /metrics
    port: prometheus-port
    relabelings:
    - source_labels: [__meta_kubernetes_pod_container_name, __meta_kubernetes_pod_container_port_name]
      action: keep
      regex: oap;prometheus-port
    - source_labels: []
      target_label: service
      replacement: oap-server
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: host_name
      regex: (.+)
      replacement: $$1
    - action: replace
      replacement: demo
      sourceLabels:
      - __address__
      targetLabel: customer
    - action: replace
      replacement: dev
      sourceLabels:
      - __address__
      targetLabel: environment
    - action: replace
      replacement: APM
      sourceLabels:
      - __address__
      targetLabel: project
    - action: replace
      replacement: Skywalking
      sourceLabels:
      - __address__
      targetLabel: group
    - action: replace
      replacement: dc01
      sourceLabels:
      - __address__
      targetLabel: datacenter
    - action: replace
      replacement: local
      sourceLabels:
      - __address__
      targetLabel: domain
    scheme: http
    scrapeTimeout: 30s
  selector:
    matchLabels:
      app: skywalking
      component: oap