encryptionsalt: v1:7J2cdGKOOok=:v1:2cIpIFrW1saxWzSx:uPmg6dI6I1/RY6/bk474e9357ODtzg==
config:
  demo:OBJSTORE.YML:
    secure: v1:fXiqTCoqRbIfnkfr:K30LqMaxWyKcQPoetjVVR1Wxrex7EnE/Ngfd9qwfP8SJd7Ap2ml75pcX1NCAHrSUYX66jLR1A6w74wua7oPTryG33HPa7s5YOVULePRyVzQdfqidyNyjVYMqm9cmA1CwP5F+hYqkopZFoD7I6IXaXEOOFrrcwtQkz+YMELXby3fflqnou+CtaGxeKJjLwz5znsCWWaeuCqbLfWNCntZndq4aGRVGHOydwxH8D41ZdPU+B0Ezup82UBo+q0m9vrAilqvwrrZhghszPCKThb5DGA8HdrO1TInTZbGWubg/KfAYDAV1RkA1Rbjl2WY21qFoQxTyGVXw/1TUhjboS+ctfMLvffPw0z2wfer6ZGESOWdmOdQgzvoij5IQDFriUUlNaL4Ab778TSZMAXrnfOFZOrNAMJehy7Tancv6YESuVovE03feiAgT72KHernIbdHES7pYSA==
  kubernetes:context: kubernetes-admin@souther
