apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: longhorn-system
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
    relabelings:
      - action: replace
        replacement: demo
        sourceLabels:
          - __address__
        targetLabel: customer
      - action: replace
        replacement: dev
        sourceLabels:
          - __address__
        targetLabel: environment
      - action: replace
        replacement: cluster
        sourceLabels:
          - __address__
        targetLabel: project
      - action: replace
        replacement: norther
        sourceLabels:
          - __address__
        targetLabel: group
      - action: replace
        replacement: dc01
        sourceLabels:
          - __address__
        targetLabel: datacenter
      - action: replace
        replacement: local
        sourceLabels:
          - __address__
        targetLabel: domain