{
 "title": "WebSite Overview",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(probe_dns_lookup_time_seconds,customer)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\"},environment)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\",environment=\"$environment\"},project)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\",environment=\"$environment\",project=\"$project\"},group)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(probe_dns_lookup_time_seconds{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"},target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_http_status_code{target=\"$target\"})"
    }
   ]
  },
  {
   "title": "Request by phase",
   "type": "graph",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (phase) (probe_http_duration_seconds{target=\"$target\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL cert expiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=\"$target\"}-time()"
    }
   ]
  },
  {
   "title": "Version of SSL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_tls_version_info{target=\"$target\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  }
 ]
}